# Generated by Django 4.1.7 on 2023-03-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aadhaar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aadhaar_number", models.CharField(max_length=12, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("gender", models.CharField(max_length=10)),
                ("age", models.PositiveIntegerField()),
                ("address", models.TextField()),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("mobile", models.CharField(max_length=14)),
                ("is_eligible", models.BooleanField(default=False)),
                ("has_registered", models.BooleanField(default=False)),
                ("has_voted", models.BooleanField(default=False)),
                (
                    "eth_public_key",
                    models.CharField(
                        blank=True, db_collation="binary", max_length=42, null=True
                    ),
                ),
            ],
        ),
    ]
